ci-cd pipeline v.1.04

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -19,7 +19,7 @@ jobs:
         run: npm run build
       - name: Handle failure
         if: ${{ failure() }}
-        run: echo "Deployment failed!" && exit 1        
+        run: echo "Build failed!" && exit 1        
   # Deploy Job
   deploy:
     # Add a dependency to the build job
@@ -41,3 +41,6 @@ jobs:
             npm install --only=prod
             npm run build
             pm2 restart brainscope-web
+      - name: Handle failure
+        if: ${{ failure() }}
+        run: echo "Deployment failed!" && exit 1               
